#FROM ubuntu:24.04
FROM ubuntu:22.04

# ------------ ENVIRONMENT CONFIGURATION
# Avoid the dreaded "fatal: detected dubious ownership in repository..." git error message
COPY resources/gitconfig /root/.gitconfig

# Avoid interactive timezone questions since Docker build has no interactive capability
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# ------------ INSTALLS AND UPDATES
# Basic Build Tools
RUN apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy
RUN apt-get -qy install build-essential git
#NISOM Cross-compiler
# GCC 6.0
#COPY resources/NISOM/oecore-x86_64-cortexa9-vfpv3-toolchain-6.0.sh /root/oecore-x86_64-cortexa9-vfpv3-toolchain-6.0.sh
#RUN chmod a+x /root/oecore-x86_64-cortexa9-vfpv3-toolchain-6.0.sh && /root/oecore-x86_64-cortexa9-vfpv3-toolchain-6.0.sh -y
#ENV PATH="/usr/local/oecore-x86_64/sysroots/x86_64-nilrtsdk-linux/usr/bin/arm-nilrt-linux-gnueabi:${PATH}"
# GCC 2.4.2
RUN apt-get install python3 -y && ln -sf /usr/bin/python3 /usr/bin/python
COPY resources/NISOM/oecore-x86_64-armv7a-vfp-neon-toolchain-2.0.sh /root/oecore-x86_64-armv7a-vfp-neon-toolchain-2.0.sh
RUN chmod a+x /root/oecore-x86_64-armv7a-vfp-neon-toolchain-2.0.sh && /root/oecore-x86_64-armv7a-vfp-neon-toolchain-2.0.sh -y
ENV PATH="/usr/local/oecore-x86_64/sysroots/x86_64-nilrtsdk-linux/usr/bin/armv7a-vfp-neon-nilrt-linux-gnueabi:${PATH}"
# Fix the issue with redundant definitions of some in6 structs by replacing the cross toolchain in6.h file with one that
# comments out the redundant defs
COPY resources/NISOM/in6_hack_fix.h /usr/local/oecore-x86_64/sysroots/armv7a-vfp-neon-nilrt-linux-gnueabi/usr/include/linux/in6.h

# Run the command to build iperf
#ENTRYPOINT ["/bin/bash"]
CMD ./configure --host=arm-nilrt-linux-gnueabi --enable-static --disable-shared; make